@startuml ホテル予約システム


actor 利用者 #DDDDDD;line:Black;line.bold;
actor 看護師 #DDDDDD;line:Black;line.bold;

rectangle 診療予約システム{
usecase 予約システムに接続
usecase 名前と電話番号を入力して登録
usecase 予約と確認
usecase あなたの順番の画面
usecase メニュー画面
usecase 今の順番の画面

}
利用者 --> メニュー画面
メニュー画面 --> 予約と確認 : 名前と電話番号を入力して登録
予約と確認 -> あなたの順番の画面 : 名前と電話番号を入力して確認ボタンをおす
予約と確認 -> メニュー画面 :　名前と電話番号を入力して削除ボタンをおす
あなたの順番の画面 -> あなたの順番の画面 : 登録番号の表示 
今の順番の画面 <-- 看護師 :診察が終了後、現在の患者番号を増やす
@enduml