@startuml

[*]-> メニュー画面
メニュー画面-> [*]  
メニュー画面 -> 予約と確認 : 予約の登録 
メニュー画面 -> 今の順番 :患者の番号\nを追加
今の順番-->メニュー画面 :診察中の\n患者の番号\nを表示
予約と確認-->あなたの順番 :電話番号\nを入力 
予約と確認-->あなたの順番 :名前を\n入力
予約と確認--> メニュー画面 :電話番号か\n名前を入力し\n予約取り消しボタン\nを押す
あなたの順番-->メニュー画面 : 登録者番号を\n表示

@enduml