@startuml
hide footbox
Actor 受注係 as member
participant ":注文登録画面" as boundary <<boundary>>
participant ":商品1" as control <<entity>>
participant ":商品2" as control2 <<entity>>



activate member
member -> boundary : 商品を注文する

activate boundary
boundary -> control : 商品情報を表示する支持を送る
activate control
activate boundary
boundary -> boundary : 注文情報を表示 
deactivate boundary
control --> boundary :商品情報
deactivate control
deactivate boundary

member -> boundary: 商品情報の確認 
activate control2

boundary --> control2 : 商品情報 

deactivate boundary        
deactivate member       
    

' control -> entity : <<create>>\n1.1.1生成():
' control -> entity : 1.1.2会員情報取得():<<create>>
' control <- entity : 登録会員情報


@enduml