@startuml
hide footbox
Actor ユーザ as member
participant ":ブラウザ" as boundary <<boundary>>
participant ":webサーバー" as control <<control>>
participant ":画像サーバー" as server


activate member
member -> boundary :リンクボタンを押す
activate  boundary
    boundary -> control : 画像ファイル名を渡す
    activate control
    
    activate server
    control -> server: 画像ファイルを探す
    server --> control : 画像ファイル
    server -> server : 画像ファイルを探す

    boundary <-- control : htmlと画像ファイル 
        
    member <-- boundary :画像の閲覧
        
deactivate member       
deactivate boundary
deactivate control
    

' control -> entity : <<create>>\n1.1.1生成():
' control -> entity : 1.1.2会員情報取得():<<create>>
' control <- entity : 登録会員情報


@enduml