@startuml ユースケース図

actor 利用者

rectangle ホテル宿泊予約{
usecase キャンペーン
usecase ログイン
usecase (<u>予約</u>\n拡張点\nキャンペーン中なので割引)


}
キャンペーン.> (<u>予約</u>\n拡張点\n金種を指定する): << include >>
(<u>予約</u>\n拡張点\n金種を指定する).> ログイン: << extend >>
利用者 --> (<u>予約</u>\n拡張点\n金種を指定する):<< extend >>
@enduml