@startuml

actor ユーザー #DDDDDD;line:Black;line.bold;
actor 光センサ #DDDDDD;line:Black;line.bold;

rectangle ライントレーサー{
usecase 電源スイッチを押す
usecase 右旋回する
usecase 左旋回する
usecase 右境界線上を進む
usecase ボタンを押してシステムを停止

}

ユーザー --> 電源スイッチを押す

光センサ --> 右旋回する :暗いと判断
光センサ --> 左旋回する :明るいと判断 
右旋回する --> 右境界線上を進む
左旋回する --> 右境界線上を進む


@endUml