@startuml
class ライントレーサー{
- 光センサー1個
- 左右モータ
- CPU
- 電源SW
} 

class 光センサー{
} 

class 右モータ{
}

class 左モータ{
}


class 電源SW{
}

電源SW --> ライントレーサー :入
電源SW --> ライントレーサー :切
光センサー --> 左モータ: <ON>
光センサー --> 右モータ: <OFF>
光センサー --> 右モータ: <ON>
光センサー --> 左モータ: <OFF>
右モータ --> ライントレーサー :左旋回
左モータ --> ライントレーサー :右旋回