@startuml 並列処理
title フォークで並列処理
start
:米を洗う;
fork
:野菜を洗う;
fork
:野菜を切る;
fork again
:みじん切りにした玉ねぎを炒める;
end fork
fork
:玉ねぎを炒める;
:ジャガイモとニンジンを炒める;
:牛肉を炒める;
end fork

:コンソメを入れて煮る(中火20分);
:ルーを入れてさらに煮る(弱火10分);
:牛乳を入れる(目分量);
fork again
:ターメリックを入れる;
:米を炊く(45分);
end fork
:それぞれ盛り付ける;
stop
@enduml