@startuml

left to right direction
object "<u>顧客1: 顧客</u>" as u1 {
氏名 =高田理恵
住所 = 
}
object "<u>顧客2: 顧客</u>" as u2 {
氏名 =大坪直之
住所 = 

}
object "<u>重要顧客: 重要顧客</u>" as u3 {
氏名 =高橋洋平
住所 = 
}

object "<u>注文詳細1: 注文</u>" as t1 {
注文日 =
11月21日
12月23日 
数量 =2台
}
object "<u>注文詳細2: 注文</u>" as t2 {
注文日 = 11月21日
数量 = 2台

}
object "<u>注文詳細3: 注文</u>" as t3 {
注文日 = 12月30日 
数量 = 1台

}

object "<u>商品1: 商品</u>" as g1 {
商品名 = テレビ
型式 = V12345
}
object "<u>商品2: 商品</u>" as g2 {
商品名 = 冷蔵庫
型式 = R8765
}
object "<u>商品3: 商品</u>" as g3 {
商品名 = プロジェクタ
型式 = P1122
}
u3 -- t1
u3 -- t2
t1 -- g2
t2 -- g1
t3 -- g3
u2 -- g3
u1 -- t1
@enduml
