@startuml

left to right direction
object "<u>301号室: 部屋</u>" as 301 {
タイプ = シングル
価格 = 11000
キャンペーン = 9000

}
object "<u>302号室: 部屋</u>" as 302 {
タイプ = シングル
価格 = 11000
キャンペーン = 9000

}
object "<u>303号室: 部屋</u>" as 303 {
タイプ = シングル
価格 = 11000
キャンペーン価格 = 9000
}

object "<u>利用者情報1: 利用者</u>" as userA {
名前 = Aさん   
住所
電話番号
}
object "<u>利用者情報2: 利用者</u>" as userB {
名前  = Bさん  
住所
電話番号
}

301 -- userA
303 -- userB
@enduml
