@startuml
|顧客|
|顧客|

|スタッフ|
|スタッフ|

|厨房|
|厨房|

|スタッフ|
start
:挨拶をする;
|スタッフ|
:テーブルに案内する;
|顧客|
:注文する;
|スタッフ|
:注文を決める;
|スタッフ|
fork
:注文を受ける;
|顧客|
:代金を払う;
|スタッフ|
:空欄;
fork again
:伝票を書く;
|厨房|
:空欄;
|スタッフ|
end fork
:料理人に注文を伝える;

if () is (<color:red>[テイクアウト]) then
:予約を行う;
else (<color:blue>[店内])
:ユーザー名とパスワードをもう一度入力する;
endif
:料理を作る;
|スタッフ|
|顧客|
:商品を受け取る;
stop
